### ISSUE TITLE
compute_dti has dependency on the data format in nifti

### ISSUE THREAD

**Issue by htakemur** [ucl-mig/iqt#3]
Hello, 

Thank you very much for sharing code of interesting work! 

I am starting to have a look at code. Then I figure out the issue: 

The code compute_dti.m may assume that diffusion data is saved as double in nifti files. When I use the nifti file in which data matrix is saved as int16, I got a following message:

`??? Error using ==> mtimes Integer data types are not fully supported for this operation. At least one operand must be a scalar.`

at 

`X = W*X`

in compute_dti.m

This is because "*" does not accept the matrix saved as int. 

I transformed the matrix in double, by changing the code 

`dw = nii.img`

into 

`dwi = double(nii.img)`

Then the code seems to be working. (I am not sure whether the code runs correctly or not, but at least it worked until the end without producing error).

**Comment by solitaryangler** [comment]
Hi,
thanks a lot for pointing this out. I have updated the code now.
Best,
 -Auro

**Comment by htakemur** [comment]
Thank you very much! (Sorry for the delayed response)
